# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = '$directory$git_branch$git_status$character'
right_format = '$status $nix_shell $container $username$hostname'

[package]
disabled = false

[username]
show_always = false
format = '[$user]($style)'
style_user = '#FF0066'
style_root = 'bold red'

[hostname]
ssh_only = true
style = 'bold blue'
format = '[@](white)[$hostname]($style)'

[container]
style = 'dimmed white'
format = '[$name]($style)'

[status]
style = 'bold red'
symbol = ' '
sigint_symbol = ' '
not_found_symbol = ''
signal_symbol = ''
format = '[$symbol]($style) '
map_symbol = true
disabled = false

[directory]
truncate_to_repo = false
truncation_length = 8
truncation_symbol = '…/'
style = 'cyan'

[git_branch]
disabled = false
style = 'green'
format = '[$branch ]($style)'

[git_status]
style = 'yellow'
format = '[$all_status$ahead_behind]($style)'

# Modify the display for each git status indicator to show count after symbol
stashed = '\$$count '
ahead = '⇡$count '
behind = '⇣$count '
diverged = '⇡$ahead_count⇣$behind_count '
untracked = '?$count '
modified = '!$count '
staged = '+$count '
renamed = '»$count '
deleted = '×$count '
conflicted = '≠$count '

[git_commit]
disabled = true

[git_state]
disabled = true

[nix_shell]
format = ' [$state]($style)'

